### PR TITLE
 feat: custom dictionary

### PR DESCRIPTION
**Pull request by bushiyi**
hello, I have been using your plugin to view English documents, but some technical terms are always translated in a mess, so I would rather not translate these words, I want to skip this words, but I didn't find a plugin with such functionality, finally I found this plugin is open source, thanks for your contribution.

   There should not be many users who have the same needs as me, but I believe it should be a little helpful to those Chinese programmers who are not good at English like me.
   please tell me your suggestion.

 **The functions are as follows:**

1. Allow keywords to be skipped during web page translation and give replacement values
2. Languages that do not contain separators in their grammars, such as Chinese and Burmese, are not supported, it can be added, but it is actually invalid

### CODE REVIEW

**Comment by kesc11** [comment]
#299

**Comment by FilipePS** [comment]
I found a very strange bug.
Add this word `willkommen` to the custom dictionary.
Now translate this site https://de.wikipedia.org/wiki/Wikipedia:Hauptseite.
Note that the text `Willkommen bei Wikipedia` has been translated to `Willkommen attack Wikipedia, the free encyclopedia`, which is wrong.
Now restore the page to the original language, open devtools, select the `<html>` element and copy the outer HTML. Create an HTML file and paste the previously copied content. Open the file and translate it. In this case the text will be translated to `Willkommen on Wikipedia`.

**Comment by kesc11** [comment]
@FilipePS  
I reproduced this problem, and tried it manually on the translation site.Google Translate misidentified this text as **Guarani language**. If I manually set it to **German**, it will translate better.
But the problem actually lies in **the hidden newlines**, now I replace all the newlines with spaces, and remove the consecutive spaces,now the translation is better，But actually the translation is not perfect.
But I have no better way, the language is very complicated. My original intention was to skip some professional terms, If only filtering **nouns**, I think Google can translate better.
### E.g  `Willkommen bei Wikipedia`

skip `Wikipedia`   ,  `Willkommen bei #1%1#1#2%2#`  will be sent to google.

skip `willkommen`   ,  `#1%1#1#2%2# bei Wikipedia`  will be sent to google, I think it's hard for Google to know how to properly translate `bei` .

I printed this text and found `<pre>#1%1#1#2%2# bei \n              Wikipedia</pre>` ,  double-click this text to find a newline, it affects the semantics, which I think can be safely removed.

Wikipedia – Die freie Enzyklopädie 和另外 2 个页面 - 个人 - Microsoft​ Edge 2022_9_16 12_48_12

**Comment by FilipePS** [comment]
In the request made to Google translator there is a reason for the `<pre>` tag to be sent. It's to keep the text formatting, newlines, etc...
This is especially useful when translating selected text, but also when translating `.txt` files, `<pre>` tags and other elements with CSS that preserves text formatting.
In this case it is not good to remove newline character and space.

Another bug: in the custom dictionary list, the first item in the list seems to be ignored.

When adding an item to the dictionary the text should be trimmed.

-----------------------------------------------
Now about those characters that you send to google translator `#1%1#1#2%2#` in place of the original word.
This actually harms the translation, and does not guarantee that these characters will be preserved. There may be combinations of sourceLanguage and targetLanguage that remove or modify these characters.

One approach that might be better is to use the own features that google html translator provides.

This HTML markup:
```html
<p>Willkommen bei Wikipedia</p>
```
Create this **`sourceArray3d`**:
```json
[["Willkommen bei Wikipedia"]]
```
And this will be sent to Google translator:
```json
"<pre>Willkommen bei Wikipedia</pre>"
```
Which will answer this:
```json
[ "<pre>Welcome to Wikipedia</pre>", "de" ]
```

---------------------------------------------------------------
If the word `Willkommen` is in my custom dictionary:

I can simulate this HTML markup:
```html
<p><span>Willkommen</span> bei Wikipedia</p>
```
Create this **`sourceArray3d`**:
```json
[["Willkommen", "bei Wikipedia"]]
```
And this will be sent to Google translator:
```json
"<pre><a i=0>Willkommen</a><a i=1>bei Wikipedia</a></pre>"
```
Which will answer this:
```json
[ "<pre><a i=0>Welcome</a> <a i=1>to Wikipedia</a></pre>", "de" ]
```

I think you may have already gotten the idea.

**Comment by kesc11** [comment]
Considering your suggestion, I tried to handle sourceArray3d directly, since I had to find it in the translation result, I created this 
`"<pre><customSkipWord i=0>1</cousmerskipWord><a i=1> bei \n              Wikipedia</a></pre>"`

But I encountered a problem when I restored it. I found that there is a lot of regex
`result.match(/\<a\si\=[0-9]+\>[^\<\>]*(?=\<\/a\>)/g)`
 `if (dontSortResults) `
 and my text appeared `<b>,` etc.
I'm so sorry ， I didn't understand how to deal with it.


so Now I still only deal with text, instead of `sourceArray3d`,  I modified the start mark to be `'<customskipword>'` ，modified the end mark to be `'</customskipword>'`

from  `<pre>#1%1#1#2%2# bei \n Wikipedia</pre>`

to  `<pre><customskipword>1<customskipword>  bei \n              Wikipedia</pre>`


---
Question about newlines

1.Line breaks in the html text are replaced by **spaces**, if this  `\n`  means a new paragraph, then this has no effect on semantics, because there are still punctuation marks.

2.I observed that  **translating selected text**  does not call the **filter keyword method**, And I think that the function of **custom dictionary** should only appear in **web page translation**, after all, my purpose is just to facilitate reading technical documents in English, haha.

3.The `\n` will be deleted only if the keyword hits, other texts are not affected.

Since the user has used the dictionary function, is it acceptable to remove line breaks for a small number of sentences where keywords appear? For a large piece of text, I consider removing line breaks only for **the 30 characters before and after the keyword appears**, in order to minimize the possible impact on semantics.

---

Another bug: in a custom dictionary list, the first item in the list seems to be ignored.

Can you provide a reproduction of this problem?

**Comment by kesc11** [comment]
This may not be possible, because I don't know how to concatenate `result[0] + "bei" + result[1]` .

Suppose I record the `keywords ` before sending them to Google , and save their location. But because I don't have a `mark`  in `results`, I don't know which sentence corresponds to which information. The plugin is translated in real time as the page scrolls, there are multiple `results`, but there is only one `Map` (save my filtered information).

That's why I have a dedicated tag `<customskipword>  15 </customskipword>` .

Through this tag , I determine the position where the keyword appears, and  according to this number such as ` 15 `,  take out the `original keyword` carrying the capitalization information in the `Map`.

**Comment by kesc11** [comment]
I found some bugs, ` <customskipword>11</customskipword>` was **escaped**.

and then after regular  ` result.match(/\<a\si\=[0-9]+\>[^\<\>]*(?=\<\/a\>)/g)`, 
 there are some problems in some cases

 I am going to modify `escapeHTML `to let him skip my `<customskipword>`, how do you feel

**Comment by FilipePS** [comment]
You will iterate over sourceArray3d and consequently over sourceArray2d, when you find a string with a word from the custom dictionary. You will remove the word and split the string into one of positions.
If your sourceArray2d had size 5, when removing a word it will have size 6. Then you will need to save the indicies that were modified. After translating the sourceArray3d, just iterate again, and cancatenate the indices you had previously split.

Note that at no time will you need to deal with any tags or text markup.

And use the latest translationService from Github, it has been refactored recently, and will soon split into several files.

**Comment by kesc11** [comment]
open this link   https://docs.temporal.io/temporal/

for `The Temporal Platform explained.` i want to skip `Temporal ` 
After my processing now this is sent to google `<pre><a i=0>The </a><a i=1> Platform explained.</a></pre> ` 
but the result returned    `['。', '平台解释道']`  

I open the Google webpage to **manually translate** it, but the result is different from the program. What request parameters does this have to do with?  
And when I set the plugin to: translate to `German`, the result is normal, I don't know what's wrong with `Chinese`. 

I guess if send to google with my tag, for example ` XXX Platform explained`, it treats unrecognized `xxx ` as a noun，and contact contextual translation，So maybe the translation would be better.


Now I have done as you said not to send any other text to Google,  now this function will not display properly in some cases，but  this problem comes from `Google Api`  , and I think there's no way to deal with it.  

But I feel that this anomaly should be acceptable?

**Comment by kesc11** [comment]
I didn't expect web page translation to be so complicated.

屏幕截图 2022-09-23 181020

**Comment by FilipePS** [comment]
- Although `storage.local` cannot store `Map` it can store `Object`, it is not necessary to convert to JSON string.
- You can convert a `Map` to `Object` just like `Object.fromEntries(myMap)`.
- And to turn an `Object` into a `Map` again, first you need to convert it into a 3D array `new Map(Object.entries(myObject))`.
- About the dot character being at the beginning of the string. The `dontSortResults` setting solves this problem in this specific case.

**Comment by kesc11** [comment]
By not sorting, the punctuation is normal.
But in this sentence `Spring `should be at the beginning
`Spring `and `平台 ` should be next to each other

屏幕截图 2022-09-26 140055

**Comment by kesc11** [comment]
I think it might really be necessary to send the tags in the past, since a lot of the sentences are split weirdly 


still that page


a


`The Temporal Cluster is open source and can be operated by you. The Temporal Cloud is a set of Clusters operated by us.`

was dismantled 

屏幕截图 2022-09-26 140055

Now the translation result is very poor and the grammar is not smooth

**Comment by kesc11** [comment]
I tried translating it into Portuguese, and the amazing thing is that the translation is normal, but for Chinese, the translation is very bad

**Comment by bushiyi** [comment]
I came up with a good idea, now I still only deal with it in the `pageTranslator `and still send special mark to Google.

But the difference is that **I can know if Google has broken my translation** , I will catch these exceptions, and re-invoke the `backgroundTranslateSingleText ` method for this small portion of text. (no custom dictionary)

There are other cases, such as the original text contains my markup, etc. are also captured.

**Comment by FilipePS** [comment]
I was thinking, my definition of 3D array and 2D array is wrong.

This is not a 2D array it's just a simple array:
`["hello", "world!"]`

And this is not a 3D array, it's just a 2D array:
`[["hello", "world!"], ["You", "Are", "Welcome."]]`

**Comment by FilipePS** [comment]
Thanks for your contribution.
And as I said before preserving all spaces is important for the current version of the extension.
So I took the liberty to change the code, and the spaces will only be removed if the person has at least one word defined in the dictionary.

**Comment by bushiyi** [comment]
haha, this is my first PR on Github and I'm really happy to be merged.

I'm very busy recently and I'm going on a business trip. I think I'll optimize this little function when I'm free.

**Comment by FilipePS** [comment]
I refactored some more files. Among them the `config.js` file.
And I changed the `toObjIfTypeIsMap` and `toMapIfTypeIsObj` functions to two other functions called `fixObjectType` and `toObjectOrArrayIfTypeIsMapOrSet`.
The code was changed to mainly not convert all Objects into Map. The `hotkeys` setting for example is an object and should not be converted to a Map causing certain bugs.

**Comment by FilipePS** [comment]
I was researching and Microsoft Translator (Bing) supports dynamic dictionaries. I think this can be implemented in the extension.
https://learn.microsoft.com/azure/cognitive-services/translator/dynamic-dictionary

**Comment by FilipePS** [comment]
I have found that if I set the `translate` attribute to `no` **google translate** will skip translating that marked text.
```html
<pre><a i=0>The </a><a i=1 translate="no">Temporal </a><a i=2> Platform explained.</a></pre>
``` 
```html
<pre><a i=0>时空</a><a i=1 translate='no'>Temporal</a><a i=2>解释道。</a></pre>
```

**Comment by heyline** [comment]
Your above results are indeed a bit bad. 
I tried these three translation engines, and for Google,  `<a i="0">这 </a><a i="1" translate="no">Temporal </a><a i="2">平台说明。 </a>` , the translation is indeed very good.
 After all, we just want to skip the translation of nouns.  Let me find a time to study it

**Comment by FilipePS** [comment]
I won't have an example here, but I've already encountered a problem with this method. In one test the word marked `notranslate` was repeated outside of any `<a>` tags. In another test, one of the `<a i=X>` tags disappeared. Perhaps this works better when using Yandex as the translation engine.

And Bing's dynamic dictionary seems to work fine.
Copy this text below and translate it on this website: https://www.bing.com/translator
```html
The <mstrans:dictionary translation="Temporal">Temporal</mstrans:dictionary> Platform explained.
```

**Comment by heyline** [comment]
Indeed, these translation engines are a black box, and what he returns is not always certain.The function of this bing is really amazing, this is the custom dictionary I want.

**Pull request merged**
