### PR TITLE
Revamp translate document popup

### PR DESCRIPTION
**Pull request by CaganAgabey**
Hi, this pull request revamps the whole document translating system. Now, everything is in one section and just buttons/texts are disappearing. Also, it includes lots of design enhancements and script improvements.

### CODE REVIEW

**Comment by FilipePS** [comment]
Why did you remove error messages?
It is important for the user to know that Google does not support pdf above 10MB and if for any reason the extension cannot download the pdf, the user should also be warned about it.

**Comment by FilipePS** [comment]
And that message that the PDF needs to be converted to HTML only needs to be shown before the user selects the conversion service, not while downloading the PDF.

**Comment by CaganAgabey** [comment]
image
image
Please look carefully. There's still an error system, even it gives a special error for Google Translate on files larger than 10 MB.
I didn't decide to remove PDF to HTML conversion message on downloading because I wanted to create a fixed popup size, and I made an error message with the same height of translation service selection block. Should I remove that message and add it's height to the error message?

**Comment by CaganAgabey** [comment]
image
This catch block is still here too.

**Comment by CaganAgabey** [comment]
- Message that the PDF needs to be converted to HTML is now shown just when selecting the service
- Fixed selecting services buttons were disappearing when you click the blank between two service buttons
- Fixed "pleaseWait" variable's target element was wrong
- Fixed Google is not supporting above 10 MB text was appearing with the please wait text when you click google and click another service on files above 10 MB
And improved javascript code.

**Pull request merged**
