### PR TITLE
fix: keep original whitespace characters at beginning and end of TextNode

### PR DESCRIPTION
**Pull request by lukaszpolowczyk**
Often the Translator adds or removes spaces at the beginning and end of the TextNode, and thus the text shifts (by extra spaces), or the translated text is unreadable and cannot be copied (because, for example, there are no spaces between sentences.

This Pull request fixes this problem for both simple text and attributes.

Fixes https://github.com/FilipePS/Traduzir-paginas-web/issues/441

### CODE REVIEW

**Comment by FilipePS** [comment]
Could you please unarchive you repository https://github.com/lukaszpolowczyk/Traduzir-paginas-web

**Comment by lukaszpolowczyk** [comment]
@FilipePS Done.

**Comment by FilipePS** [comment]
Thanks for the contribution.
And I just realized that this **merge/rebase/squash** ended up adding the old `/contentScript/pageTranslator.js` file

**Comment by FilipePS** [comment]
Languages such as Chinese and Japanese do not have whitespace word separation.
This pull request makes all the texts stick together and truncated, so for now I disabled the code.
https://github.com/FilipePS/Traduzir-paginas-web/commit/42b75af04990c1d22310643acd97ec0a9cd2fbeb

**Comment by lukaszpolowczyk** [comment]
@FilipePS Probably need more advanced rules, tailored to language pairs.

**Pull request merged**
