### PR TITLE
Revamp translate text popup

### PR DESCRIPTION
**Pull request by CaganAgabey**
Hi, this pull request completely revamps the translate text popup. I didn't touch the popup for sites that don't allow inject scripts.
It adds a gaussian blurred background if the browser supports it, and more design enhancements.
Chromium browsers support the gaussian blurred background by default, but in Firefox you should change `layout.css.backdrop-filter.enabled` in about:config. If not enabled, there will be a black background with 20% transparency.
Also, it adds a copy button. (Issue #319)
I removed the dark/light mode thing because there's no need, there's a transparent background.

### CODE REVIEW

**Comment by CaganAgabey** [comment]
Now updated the popup for NoScript sites too.

**Comment by CaganAgabey** [comment]
Fixed button's appearance issue on the non-blur mode in normal translate text popup and added light mode support for popup in NoScript sites.

**Comment by CaganAgabey** [comment]
This commit should fix button appearances on blur mode with dark background

**Comment by CaganAgabey** [comment]
These commits put the copy and listen buttons to the right of the translated text instead of the bottom bar, also some sizing and positioning improvements

**Comment by CaganAgabey** [comment]
- Fixed the original text div on address bar popup
- Fixed small white dots on left of the copy, listen buttons
- Slightly improved the scrollbars

**Comment by FilipePS** [comment]
When selecting too much text the layout is broken.

And the width of the popup should automatically increase to allow it to read larger texts better. Just like before.

Although at first I thought the copy and listen button would look good on the popup side, when selecting a lot of text these buttons take the place of the scrollbar.
Probably the only solution is to keep it in the original location, at the bottom of the popup.

image

**Comment by CaganAgabey** [comment]
Is there a problem like this on the script popup?

**Comment by FilipePS** [comment]
I fixed the problems here [""](https://github.com/FilipePS/Traduzir-paginas-web/commit/79b8984ccd3f995b4171ee1336fdf1ebd650100e) and here [""](https://github.com/FilipePS/Traduzir-paginas-web/commit/5c3e812771bbeb0753eaa861e06455e6705698e7).

I put the copy and listen buttons together with the other buttons. Otherwise they would be in the scrollbar location.

The main factor causing the layout break is the height of the text area. The height of the textarea together with the height of the other elements added together was greater than the maximum height allowed by the popup, causing the layout break.
So I reduce the max-height a little bit. I also put a slightly more generous max-width.

And another thing. You changed the z-index from 2147483647 to 2. This is not good.
This easily allows other elements of the site to be on top of the popup. So I fixed that too.

**Comment by FilipePS** [comment]
I fixed the problems here https://github.com/FilipePS/Traduzir-paginas-web/commit/79b8984ccd3f995b4171ee1336fdf1ebd650100e and here https://github.com/FilipePS/Traduzir-paginas-web/commit/5c3e812771bbeb0753eaa861e06455e6705698e7.

I put the copy and listen buttons together with the other buttons. Otherwise they would be in the scrollbar location.

The main factor causing the layout break is the height of the text area. The height of the textarea together with the height of the other elements added together was greater than the maximum height allowed by the popup, causing the layout break.
So I reduce the max-height a little bit. I also put a slightly more generous max-width.

And another thing. You changed the z-index from 2147483647 to 2. This is not good.
This easily allows other elements of the site to be on top of the popup. So I fixed that too.

**Comment by CaganAgabey** [comment]
Thanks

**Pull request merged**
