### PR TITLE
Optimize crowdin.js and getLanguagesNames.js

### PR DESCRIPTION
**Pull request by CaganAgabey**

### CODE REVIEW

**Comment by FilipePS** [comment]
The `crowdin.js` file shouldn't have hidden errors.
And in the `getLanguagesNames.js` file a lot of useful code has been removed. Try deleting the `out` folder and see if anything happens when you run this script.

**Comment by CaganAgabey** [comment]
`crowdin.js` file doesn't have any hidden errors currently. extract-zip module's newer versions have 2 arguments on the function, so I added the catch block at the end.

I didn't remove anything in the `getLanguagesNames.js` file, I just combined per-service functions into one function, also did small code cleanup/improvement.
Also, I pushed a new commit on that file, to fix some errors I found after trying it in the proper way. This version works without any issue.

**Comment by FilipePS** [comment]
The script `getLanguagesNames.js` is not working correctly with **--bing**, **--info** and **--final** commands.

**Comment by CaganAgabey** [comment]
It should work properly now.

**Comment by FilipePS** [comment]
image
This count is wrong.

**Comment by CaganAgabey** [comment]
it was a very small typo, it's fixed now

**Pull request merged**
