### PR TITLE
For custom dictionaries, adapt to the official Bing API

### PR DESCRIPTION
**Pull request by heyline**
I'm back，I spent a little time researching it before going to bed, One known problem now is that when I translate the web page and switch from bing to google, because the markup has changed, the markup appears on the page in plaintext, and the page has to be refreshed to be normal, I haven't looked at the reason carefully, let me go to sleep first

### CODE REVIEW

**Comment by FilipePS** [comment]
Use `currentPageTranslatorService` instead of `twpConfig.get("pageTranslatorService")`

**Comment by FilipePS** [comment]
In `filterKeywordsInText` you should also use `currentPageTranslatorService`.
The `currentPageTranslatorService` variable is only updated when you restore/translate again, this prevents half of the page from being translated by one translation service and the other half by another, and also allows two different tabs to be translated simultaneously using different translation services .

And the call to `twpConfig.get("customDictionary")` should only exist once, and be in the `translatePage` function.
And the code to reorder the **customDictionary** should also be in the `translatePage` function, it is unnecessary to reorder each time **textNode** is translated.

The `handleCustomWords` function is asynchronous. And if it resolves after the page is restored, will the **node** be translated? I believe so, and this should not happen.

**Comment by heyline** [comment]
On the last point, I re-called backgroundTranslateSingleText because maybe the translation might throw an exception, which caused the method to become asynchronous, do you have a good way for me to tell if the user canceled the translation

**Comment by FilipePS** [comment]
I made some fixes.

> The handleCustomWords function is asynchronous. And if it resolves after the page is restored, will the node be translated? I believe so, and this should not happen.

I'm going to fix this in **version 9.9**, it's planned to refactor several files.

**Pull request merged**
