### PR TITLE
New messages.json translation (Latvian)

### PR DESCRIPTION
**Pull request by Coool**
Latvian translation by Coool (github.com/Coool)

### CODE REVIEW

**Comment by FilipePS** [comment]
All contributions on Crowdin are automatically synced to this repository after pull requests like this one https://github.com/FilipePS/Traduzir-paginas-web/pull/434.

If any translation in this pull request file is not on Crowdin, please send it to Crowdin.
Only make pull requests that change the `messages.json` file if the file is in English, otherwise use Crowdin.

**Comment by Coool** [comment]
Using Crowdin you loose history of contributors and credits.

**Comment by FilipePS** [comment]
Unfortunately most people don't know how to use Github, so there's no other way. But I can create a file here on Github with the List of all Crowdin Contributors.

**Comment by FilipePS** [comment]
Crowdin has a list of members, but I think only I can see it.
In addition he has the complete and public history of each contribution, [see](https://crowdin.com/project/translate-web-pages/activity-stream).
It probably even has the old "messages.json" contributions list that I had to delete to add synchronization between Crowdin and Github. (Maybe this was a mistake, but it was the only way I could find).
I could use this history to create a Top Tier of Crodin's biggest contributors, etc...

**Comment by Coool** [comment]
Anyway, Git are better to preserve history of contributors.

**Comment by FilipePS** [comment]
It has new strings to be translated.
You can make a pull request and it will be accepted, but don't forget to also upload it to crowdin.

**Pull request closed without merging**
